version: "3.8"

volumes:
    mysql_data:

networks:
    app_network:
        driver: bridge

services:
    app:
        container_name: app
        image: php:8.1-fpm
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        depends_on:
            - mysql
        networks:
            - app_network

    nginx:
        container_name: nginx
        image: nginx:latest
        platform: linux/x86_64
        ports:
            - 80:80
        volumes:
            - ./:/app:delegated
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app_network

    mysql:
        container_name: mysql
        image: mariadb:10.3
        environment:
            MYSQL_DATABASE: burlang
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - app_network